# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: List update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Update list
      run: |
        git config --global user.email "anonymouse@x.com"
        git config --global user.name "anonymouse"

        pip install ta
        pip install pandas

        python binance/scripts/update-macd.py

        git add .
        git commit -m "update"
        git push origin main
